# logging.level.org.springframework.data.mongodb=TRACE
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=TRACE

logging:
  level:
    root: INFO
    org.mongodb.driver.protocol.command: INFO


spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017
      database: db_test
  autoconfigure:
    exclude: 'org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration'

  application:
    name: Finance Data Api

server:
  servlet:
    context-path: /financeData
  port: 8084




# updateBalance: "10 * * * * *"
# updateCashFlowStatement: "10 * * * * *"

