spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: testDatabase
      auto-index-creation: true
  autoconfigure:
    exclude: 'org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration'
  application:
    name: Finance Data API


management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8084
  servlet:
    context-path: /financeApp
logging:
  level:
    root: INFO


