#server:
#  port: 8084
#
#
#
#logging:
#  level:
#    root: INFO
#
## updateBalance: "10 * * * * *"
## updateCashFlowStatement: "10 * * * * *"
#
#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: testdb
#      auto-index-creation: true
#  autoconfigure:
#    exclude: 'org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration'
