spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/test_db?autoReconnect=true"
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  application:
    name: Market Data API

springdoc:
  swagger-ui:
    operations-sorter: method
  api-docs:
    path: /api-docs
  show-actuator: true
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9092
server:
  port: 8084
