package org.gauravagrwl.financeData.model.documents.userAccount;

import com.fasterxml.jackson.annotation.JsonTypeName;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@JsonTypeName("InvestmentAccountDocument")
public class InvestmentAccountDocument extends AccountDocument {

    // Total Amount Invested.
    private BigDecimal amountInvestment = BigDecimal.ZERO;

    // Total Amount Returned.
    private BigDecimal amountReturn = BigDecimal.ZERO;

    // Is this Account Auto Tradeable.
    private Boolean isAutoTradable = Boolean.FALSE;

    private String ledgerTransactionCollectionName;

    @Override
    public void calculate(BigDecimal amount) {
        // TODO Autogenerated method stub
        throw new UnsupportedOperationException("Unimplemented method 'calculate'");
    }

//    @Override
//    public MappingStrategy<InvestmentAccountStatement> getMappingStrategy(String profileType) {
//        MappingStrategy<InvestmentAccountStatement> headerColumnNameMappingStrategy = new HeaderColumnNameMappingStrategyBuilder<InvestmentAccountStatement>()
//                .withForceCorrectRecordLength(true).build();
//        headerColumnNameMappingStrategy.setProfile(profileType);
//        headerColumnNameMappingStrategy.setType(InvestmentAccountStatement.class);
//        return headerColumnNameMappingStrategy;
//    }

}